=== NIIT-2017/Java-lab-2/target/classes/menuSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="menu">
		<xs:complexType>
			<xs:sequence>
			<!-- <xs:sequence> задает жесткую последовательность подэлементов,
				но здесь необязательна поскольку подэлемент только один <item> -->
				<xs:element name="item" maxOccurs="unbounded">
				<!-- максималное количество вхождений item не ограниченно <maxOccurs="unbounded"> по умолчанию равно 1-->
					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" type="xs:integer"/>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="volume" type="xs:integer"/>
							<xs:element name="price" type="xs:integer"/>
							<xs:element name="note" type="xs:string" minOccurs="0"/>
							 <!-- note необязательный элемент может не входить (и не входит)  <minOccurs="0"> по умолчанию равно 1 -->
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required"/>
			<!-- атрибуты для menu, должны писаться в конце, сделанны для тренировки -->
		</xs:complexType>
	</xs:element>
</xs:schema>

=== NIIT-2017/Java-lab-2/target/classes/coffeeMachineMenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- входной фаил для Javalab2 -->
<menu version = "001"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="menuSchema.xsd">
  <!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" пример пространства имён, может ссылаться на что угодно -->
  <!-- menuSchema.xsd схема для этого файла, должна находится в этой же папке (сделана для тренировки) -->

	<item>
		<id>1</id>
		<name>эспрессо</name>
		<volume>50</volume>
		<price>25</price>
	</item>
	
	<item>
		<id>2</id>
		<name>американо</name>
		<volume>100</volume>
		<price>25</price>
	</item>
	
	<item>
		<id>3</id>
		<name>кофе с молоком</name>
		<volume>150</volume>
		<price>30</price>
	</item>
		
	<item>
		<id>4</id>
		<name>капучино</name>
		<volume>150</volume>
		<price>40</price>
	</item>
	
	<item>
		<id>5</id>
		<name>капучино с шоколадом</name>
		<volume>150</volume>
		<price>40</price>
	</item>
	
	<item>
		<id>6</id>
		<name>мокачино</name>
		<volume>150</volume>
		<price>40</price>
	</item>
	
	<item>
		<id>7</id>
		<name>чай чёрный</name>
		<volume>150</volume>
		<price>20</price>
	</item>
	
	<item>
		<id>8</id>
		<name>горячий шоколад</name>
		<volume>150</volume>
		<price>30</price>
	</item>
	
	<item>
		<id>9</id>
		<name>двойной шоколад</name>
		<volume>150</volume>
		<price>40</price>
	</item>
	
	<item>
		<id>10</id>
		<name>молочный шоколад</name>
		<volume>150</volume>
		<price>35</price>
	</item>
	
</menu>
